ALTER TABLE "TeamGame" ADD COLUMN IF NOT EXISTS "minutes" DOUBLE PRECISION;
ALTER TABLE "TeamGame" ADD COLUMN IF NOT EXISTS "fieldGoalsAttempted" INTEGER;
ALTER TABLE "TeamGame" ADD COLUMN IF NOT EXISTS "freeThrowsAttempted" INTEGER;
ALTER TABLE "TeamGame" ADD COLUMN IF NOT EXISTS "turnovers" INTEGER;
